name: build

on:
  push:
    branches:
      - develop
      - master
  pull_request:
  schedule:
    - cron: '25 6 * * *'

jobs:
  buildnrun:
    name: Build iOS and Android library
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Setup NPM tools
        run: npm install -g pod-install && npm install -g react-native && npm install -g typescript
      - name: Build native libraries
        run: sh scripts/build-library.sh
